### PR TITLE
fix: prevent overwriting XRCanvas bindings

### LINKED ISSUE #65: onCreated prop on the VRCanvas prevent 'ENTERVR' from displaying
It's pretty straighforward

```
<VRCanvas
      onCreated={({ camera }) => camera.lookAt(0, 2, -2)} // having this prop prevent react-xr from working properly
>
```

having this prop prevent react-xr from working properly.
Because I guess it conflicts with this file 
https://github.com/pmndrs/react-xr/blob/master/src/XR.tsx#L164

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Fixes #65 by invoking `onCreated` when specified.

### CODE REVIEW

File: src/XR.tsx [hunk 1]
```diff
@@ -159,17 +159,29 @@ function XRCanvas({ children, ...rest }: ContainerProps) {
...
 
-export function ARCanvas({ children, sessionInit, ...rest }: ContainerProps & { sessionInit?: any }) {
+export function ARCanvas({ onCreated, children, sessionInit, ...rest }: ContainerProps & { sessionInit?: any }) {
   return (
-    <XRCanvas onCreated={({ gl }) => void document.body.appendChild(ARButton.createButton(gl, sessionInit))} {...rest}>
+    <XRCanvas
+      onCreated={(state) => {
+        onCreated?.(state)
+
+        document.body.appendChild(ARButton.createButton(state.gl, sessionInit))
```
Comment (CodyJasonBennett) [inline src/XR.tsx:182]: Should we allow `sessionInit` to be specified for `XRCanvas`?

Comment (CodyJasonBennett) [reply src/XR.tsx:182]: Doesn't seem so: https://github.com/pmndrs/react-xr/blob/master/src/webxr/VRButton.js#L5.

**Comment by sniok** [comment]
thanks!
